Hertels Kataloger/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        /*public ActionResult Index()
        {
            return View();
        }
        */
        public ActionResult Katalog(string katalog) //   /Home/Katelog/?katelog=test
        {
            string test = katalog;
            ViewBag.folder = test;

            string path = HttpContext.Server.MapPath("~/Content/Uploads/" + test);
            DirectoryInfo di = new DirectoryInfo(path);
            int amountfiles = di.GetFiles().Length;
            ViewBag.pages = amountfiles;

            return View();
        }

        public ActionResult Index()
        {
            string path = HttpContext.Server.MapPath("~/Content/Uploads/");
            var di = new DirectoryInfo(path);
            var directories = di.EnumerateDirectories()
                                .OrderBy(d => d.CreationTime)
                                .Select(d => d.Name)
                                .ToList();
            /*string[] subfolders = System.IO.Directory.GetDirectories(path);*/

            directories.Reverse();

            ViewBag.folders = new List<string>();
            foreach (string subfolder in directories)
            {
                if (subfolder != null)
                {
                    /*DirectoryInfo dir = new DirectoryInfo(subfolder);*/
                    string folder = string.Format(subfolder);

                    ViewBag.folders.Add(folder);
                }
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Hertels Kataloger/WebApplication1/Controllers/UploaderController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class UploaderController : Controller
    {
        // GET: Home
        [HttpGet]
        public ActionResult Uploader()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Delete(string katalog)
        {
            string foldername = katalog;
            ViewBag.folder = foldername;

            string path = Server.MapPath("~/Content/Uploads/" + katalog + "/");
            if (Directory.Exists(path))
            {
                Directory.Delete(path, true);
            }



            return Redirect("~/Home/");
        }


        [HttpPost]
        public ActionResult Uploader(List<HttpPostedFileBase> postedFiles, String name)
        {
            string path = Server.MapPath("~/Content/Uploads/" + name + "/");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }


            foreach (HttpPostedFileBase postedFile in postedFiles)
            {
                if (postedFile != null)
                {
                    string fileName = Path.GetFileName(postedFile.FileName);
                    postedFile.SaveAs(path + fileName);
                    ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", fileName);
                }
            }


            return Redirect("~/Home/");
        }
    }
}

Hertels Kataloger/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Hertels Kataloger/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Hertels Kataloger/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@{
    int counter = 0;
    int counter2 = 0;
    int amountFolders = 0;
}
@foreach (var folder in ViewBag.folders)
{
    amountFolders++;
}
@foreach (var folder in ViewBag.folders)
{
    if (counter == 0)
    {
        @:<div class="row">
    }
    <div class="col-md-3 text-center">

        <div class="katelog">
            <a href="@Url.Action("Katalog","Home", new { katalog = folder})">
                <img style="width: 100%" src="~/Content/Uploads/@folder/1.jpg" alt="@folder" />
                <h4 style="color:white; font-weight: bold;">@folder</h4>
            </a>
            @using Microsoft.AspNet.Identity
            @if (Request.IsAuthenticated)
            {
                <a style="color: #da1f43; font-weight: bold; display: inline-block;" href="@Url.Action("Delete", "Uploader", new { katalog = folder })" onclick ="return confirm('Er du sikker på at du vil slette dette katalog: <@folder> ?');">Slet</a>
            }
        </div>

    </div>
    counter++;
    counter2++;
    if (counter == 4)
    {
        @:</div>
        counter = 0;
    }

    if (counter != 4 && counter2 == amountFolders)
    {
        @:</div>
    }
}

Hertels Kataloger/WebApplication1/Views/Home/Katalog.cshtml
@{
    ViewBag.Title = "Katalog";
}
<style>
    *{
        overflow: hidden;
    }
    #flipbook {
        width: 1152px;
        height: 752px;
    }

    #flipbook .turn-page {
        background-color: #ccc;
        background-size: 100% 100%;
    }
</style>
<div id="flipbook">
    @for (var i = 1; i < ViewBag.pages; i++) {
        string picURL = ViewBag.folder + "/" + i + ".jpg";
    <div><img width="100%" src="~/Content/Uploads/@picURL"></div>
    }
</div>

<script type="text/javascript">

    var $browserwidth = $(window).width();

    if ($browserwidth < 1200) {

    }
    var $eWidth = $browserwidth - 400;

    var $AspectRatio = 794 / 1123;

    var $newHeight = $eWidth * $AspectRatio;

    console.log($eWidth);
    console.log($newHeight);

    $("#flipbook").turn({
        display: "double",
        width: $eWidth,
        height: $newHeight,
        autoCenter: true
    });

    $(window).bind('keydown', function (e) {

        if (e.keyCode == 37)
            $('#flipbook').turn('previous');
        else if (e.keyCode == 39)
            $('#flipbook').turn('next');

    });
</script>